### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by chenyong1003** [karnikram/rp-vio#13]
Hello, thanks for sharing.  I run into the following situation, may I ask what is the cause of this?
![455BD162-FEFF-4344-8378-55266C3CF19E](https://user-images.githubusercontent.com/87304070/138060059-3e2d730c-567c-4b16-80f8-715cfbdb4432.png)

**Comment by karnikram** [comment]
Hi, I'm not sure why it's unable to find the nodes, have you sourced your workspace after building?

**Comment by chenyong1003** [comment]
I'm sorry to bother you again.  When I was running, my RVIZ did not show the track chart. Could you tell me where I set it wrong?  There is a yellow warning in my terminal, does it matter?
![CD087938-3141-48F7-B545-292B70929787](https://user-images.githubusercontent.com/87304070/138459184-58b2e572-0aff-4ad9-b379-117ff643d761.png)

**Comment by karnikram** [comment]
It doesn't look like you are running the estimator nodes or feature_tracker nodes. After building the repo and sourcing it, please run this [script](https://github.com/karnikram/rp-vio#real-world-sequences) with the dataset path argument. If your workspace is setup properly and there are no other nodes running, this should start everything properly.
