### ISSUE TITLE
 error: template argument 2 is invalid

### ISSUE THREAD

**Issue by SharineLee** [karnikram/rp-vio#14]
`rpvio_ws/src/rp-vio/rpvio_estimator/src/estimator.h:127:28: error: template argument 2 is invalid
     map<int, array<double,3>> para_N;
`

**Comment by karnikram** [comment]
Sorry, I am not sure why you are getting this error. Please check that you are using C++ 11.

**Comment by Rubensss23333** [comment]
map<int, std::array<double,3>> para_N;

**Comment by Lisiyuan555** [comment]
solved by adding std!!
