### ISSUE TITLE
Run Real time with your own camera

### ISSUE THREAD

**Issue by John-Mccarty** [karnikram/rp-vio#17]
Hi  thanks for sharing your work.
I want to run the RP-VIO in real time on pixhawk drone.
How can provide mask(segmented) plane of camera? I am using mynt-eye  and realsense 435i camera 
 thanks

**Comment by karnikram** [comment]
Hi,

You have multiple options. If you have depth information, the best would be to use a geometric plane-fitting method like [plane_seg](https://github.com/ori-drs/plane_seg). If you want to use only RGB information, you could use a plane segmentation model like the PlaneRecover model provided by us. There could be newer and more efficient models for monocular plane segmentation, but I am not up to date. Lastly, if it's a scene with known planar regions like roads, you could also use a generic segmentation model like Faster-RCNN and just provide the plane class labels in the config file as shown in the VIODE example.

For passing these segmentations to RP-VIO, you need to publish the segmentation images on a topic, and specify it in the config file as `mask_topic`.
