### ISSUE TITLE
data conversion

### ISSUE THREAD

**Issue by chenyong1003** [karnikram/rp-vio#18]
hello,may I ask why I made the mistake in the picture?
![F0DA980B-4A4B-4FA7-B0C2-7AD855285163](https://user-images.githubusercontent.com/87304070/150748753-c2e766da-b776-482c-9a2f-ae22e7c935ce.jpeg)

**Comment by karnikram** [comment]
I seee two problems:
1. rpvio_estimator is not in your path. Please make sure your workspace is sourced after building.
2. You need to use Python 3.6+ to use f-strings.

**Comment by chenyong1003** [comment]
hello.when I want to run other scenes in the OpenLORIS dateset,such as cafe. It has the following error.
![AF48C303-0C50-4E8F-8ADB-73EC2CF35C13](https://user-images.githubusercontent.com/87304070/153703133-8ab47587-323a-4626-9adf-93f731ad4ed3.png)

**Comment by karnikram** [comment]
Are you providing the plane segmentation images on `mask_topic`? If you are running on your own data you need to set that up - https://github.com/karnikram/rp-vio#own-data
