### ISSUE TITLE
ERROR while running: calculate Homography

### ISSUE THREAD

**Issue by Lisiyuan555** [karnikram/rp-vio#19]
Hello, thanks for sharing. 
I run the datasets 12-mask.bag and have this error:
$roslaunch rpvio_estimator advio_12.launch bagfile_path:=/media/li/DATA/DATASET/RP-VIO/ADVIO/12-mask.bag
OpenCV Error: Unknown error code -28 (The input arrays should have at least 4 corresponding point sets to calculate Homography) in findHomography
Did you  ever meet this situation?
![Screenshot from 2022-01-24 17-13-26](https://user-images.githubusercontent.com/68208839/150754670-062c0214-70fc-40b1-a26f-7dfaf76696b3.png)
By the way, I have tried other datasets and also met this problem.
The modifications I made to the code were only adding 'std::' in the 'map<int, std::array<double,3>> para_N;' because 'error: template argument 2 is invalid #14' as mentioned.

**Comment by karnikram** [comment]
Hi,

Can you please try with OpenCV 3.2.0 (the default version on ROS Melodic)? I think you are using OpenCV 3.4 which has a different API for findHomography.

**Comment by Lisiyuan555** [comment]
Thank you for your advice，it seems right. But after changing the OpenCV version to 3.2.0, I encountered the problem of gflags again. Reinstalling the dynamic library did not solve it, and I am continuing to find the reason. But thank you very much for your reply！
![Screenshot from 2022-02-14 10-44-57](https://user-images.githubusercontent.com/68208839/153791674-d77d75f7-f0ac-41d1-9eff-6b8e50d3a83e.png)

**Comment by Lisiyuan555** [comment]
Thanks for your advice! After installing the OpenCV 3.2.0, there is indeed no such error, but there is also no output when running. Have you ever encountered this kind of problem?
![Screenshot from 2022-02-14 15-44-09](https://user-images.githubusercontent.com/68208839/153821274-07b195db-1e84-4a70-b3a6-6d3eeb557faf.png)

**Comment by Lisiyuan555** [comment]
In fact, I found that when I run VINS-Mono, it also fails with an error：
W0214 15:41:16.821485 12349 levenberg_marquardt_strategy.cc:114] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
So the reason may be that the result is not obtained when using ceres to solve the pose
but I can't find the problem, thank you for your answer, maybe I should reinstall the whole (◞‸◟ )
