### ISSUE TITLE
I used the original vinsmono and got different results from your paper. Why is that?

### ISSUE THREAD

**Issue by ChenHuang20** [karnikram/rp-vio#2]
I used the ol_market1_config.yaml file of your rp-vio project to directly run VINS-MONO on the OpenLORIS-market-1 dataset, and got a higher accuracy than your paper (paper is 2.45, but I got Absolute Trajectory RMSE = 0.88). Why?

The evaluation tool I use is EVO, and the link is [https://github.com/MichaelGrupp/evo]

The command is `evo_ape tum groundtruth.txt vins_result_no_loop.txt -va -p --plot_mode=xyz --align --correct_scale`

Looking forward to your answer

**Comment by ChenHuang20** [comment]
The OpenLORIS-market-1 dataset is as same as yours

**Comment by karnikram** [comment]
Hi,

The error reported is without scale correction ie we do only SE3 alignment,
since VINS is expected to estimate the correct metric scale.

**Comment by karnikram** [comment]
Even without scale correction the error might not exactly be the same as
reported in the paper due to RANSAC, and other OS related delays. But the
error from RP-VIO should still be lesser than VINS-Mono.

**Comment by ChenHuang20** [comment]
Hi, bro
I run vins-mono and evaluate it with `evo_ape tum groundtruth.txt vins_result_no_loop.txt -va -p --plot_mode=xyz --align`

I get rmse = 1.128904

Then I run rpvio with `roslaunch rpvio_estimator ol_market1.launch` and evaluate it with `sh run_ol_market1.sh`

I get rmse = 1.242076

why the error from VINS-Mono still be lesser than RP-VIO?  same ol_market_config.yaml and computer

**Comment by karnikram** [comment]
Hi,

The config file which you've used is specific to RP-VIO and differs from the default VINS-Mono parameters. I just noticed that I haven't uploaded the config file that we used for evaluating VINS-Mono. Here it is for the OL sequence - 
[vins_market1_config.txt](https://github.com/karnikram/rp-vio/files/6318379/vins_market1_config.txt). Importantly, this uses the default VINS-Mono feature tracking parameters, which is what was used in our experiments.

RP-VIO needs different parameters (provided in `ol_market1_config.yaml`) than the default VINS-Mono parameters to run well since it generally focuses on smaller regions of the scene. This parameter was still fixed across all datasets for the evaluations reported in the paper. For VINS-MONO, we sticked to the default provided parameters. Your result with different parameters is certainly interesting.

Thanks for reporting and please let me know about your results with this updated config file. I will also try including the VINS-Mono evaluation scripts that we used in the repo.

**Comment by ChenHuang20** [comment]
Hi,
I run vins-mono with your config file 3 times and got 1.55, 2.22, and 1.65 rmse.
The results from VINS-Mono are more than RP-VIO.

**Comment by Gatsby23** [comment]
> Hi,
> I run vins-mono with your config file 3 times and got 1.55, 2.22, and 1.65 rmse.
> The results from VINS-Mono are more than RP-VIO.

Have you run the segmentation part ?
When I run python inference.py, I got this:

from RecoverPlane import RecoverPlane
ModuleNotFoundError: No module named 'RecoverPlane

Have you met this error before?

**Comment by ChenHuang20** [comment]
> > Hi,
> > I run vins-mono with your config file 3 times and got 1.55, 2.22, and 1.65 rmse.
> > The results from VINS-Mono are more than RP-VIO.
> 
> Have you run the segmentation part ?
> When I run python inference.py, I got this:
> 
> from RecoverPlane import RecoverPlane
> ModuleNotFoundError: No module named 'RecoverPlane
> 
> Have you met this error before?
 
I run the segmentation part，but I didn't get this error

**Comment by Gatsby23** [comment]
> > > Hi,
> > > I run vins-mono with your config file 3 times and got 1.55, 2.22, and 1.65 rmse.
> > > The results from VINS-Mono are more than RP-VIO.
> > 
> > 
> > Have you run the segmentation part ?
> > When I run python inference.py, I got this:
> > from RecoverPlane import RecoverPlane
> > ModuleNotFoundError: No module named 'RecoverPlane
> > Have you met this error before?
> 
> I run the segmentation part，but I didn't get this error

How to run the segmentation part? could you please give me some advices? What is your OS ?

**Comment by ChenHuang20** [comment]
> > > > Hi,
> > > > I run vins-mono with your config file 3 times and got 1.55, 2.22, and 1.65 rmse.
> > > > The results from VINS-Mono are more than RP-VIO.
> > > 
> > > 
> > > Have you run the segmentation part ?
> > > When I run python inference.py, I got this:
> > > from RecoverPlane import RecoverPlane
> > > ModuleNotFoundError: No module named 'RecoverPlane
> > > Have you met this error before?
> > 
> > 
> > I run the segmentation part，but I didn't get this error
> 
> How to run the segmentation part? could you please give me some advices? What is your OS ?

There is no need to run segmentation part  separately, because the segmentation part is in the datasets, just download the author’s datasets and follow the command provided by the author to run

**Comment by Gatsby23** [comment]
> > > > > Hi,
> > > > > I run vins-mono with your config file 3 times and got 1.55, 2.22, and 1.65 rmse.
> > > > > The results from VINS-Mono are more than RP-VIO.
> > > > 
> > > > 
> > > > Have you run the segmentation part ?
> > > > When I run python inference.py, I got this:
> > > > from RecoverPlane import RecoverPlane
> > > > ModuleNotFoundError: No module named 'RecoverPlane
> > > > Have you met this error before?
> > > 
> > > 
> > > I run the segmentation part，but I didn't get this error
> > 
> > 
> > How to run the segmentation part? could you please give me some advices? What is your OS ?
> 
> There is no need to run segmentation part separately, because the segmentation part is in the datasets, just download the author’s datasets and follow the command provided by the author to run

Yeah, but I wanna to use it on my dataset
