### ISSUE TITLE
no trajectory displayed

### ISSUE THREAD

**Issue by Lisiyuan555** [karnikram/rp-vio#20]
Sorry to bother you again, rviz does not show the trajectory when I run the ADVIO dataset downloaded from your official website, what could be the reason?
![Screenshot from 2022-02-18 11-53-11](https://user-images.githubusercontent.com/68208839/154616208-14c570e1-ecb3-41ec-9209-7ea14ca5d205.png)

**Comment by karnikram** [comment]
That is strange, it looks like the estimator is running. Can you do a `rostopic echo rpvio_estimator/odometry` to see if the odometry is being published? I am not hundred percent sure about the topic name.

**Comment by Lisiyuan555** [comment]
Here is the screenshots:
![Screenshot from 2022-02-24 10-33-01](https://user-images.githubusercontent.com/68208839/155446825-8fc5e954-32a9-49e8-9cb8-3045fe8caef3.png)
All covariances are 0, is the calculation result wrong?

**Comment by karnikram** [comment]
No, the covariance is neither computed nor published. But it looks like the poses are being published fine so this is probably just a visualization issue. Can you please check if the right topic is selected in rviz?

**Comment by Lisiyuan555** [comment]
OOOOh, is this right?
![Screenshot from 2022-02-24 11-23-44](https://user-images.githubusercontent.com/68208839/155452234-a40e0648-14a8-48ff-96fe-a1f70d77aa65.png)
By the way, so RP-VIO doesn't calculate covariance at all?

**Comment by Lisiyuan555** [comment]
OOOOh, is this right?
![Screenshot from 2022-02-24 11-23-44](https://user-images.githubusercontent.com/68208839/155452234-a40e0648-14a8-48ff-96fe-a1f70d77aa65.png)
By the way, so RP-VIO doesn't calculate covariance at all?
