### ISSUE TITLE
AirSim recording scripts

### ISSUE THREAD

**Issue by aqiuxx** [karnikram/rp-vio#22]
hi, thanks for sharing your great work! 
I am interested in the AirSim recording scripts
Do you have any plans to add the AirSim recording scripts ？

**Comment by karnikram** [comment]
Hi, thank you for your interest. I am unable to do a proper release with documentation now, but I've dumped whatever scripts I have with me here - https://drive.google.com/drive/folders/1XZ6ZgOrgeePikv77ZnW6feiiCX2Io8zZ?usp=sharing

Hope it helps!

**Comment by aqiuxx** [comment]
Thank you very much, it helped me a lot！
