### ISSUE TITLE
How do you align the data of d435i accelerometer and gyroscope to / imu0 topic?

### ISSUE THREAD

**Issue by ChenHuang20** [karnikram/rp-vio#3]
Hi，

I appreciate you can answer my question,

Thank you for your open source code and datasets.

Your work has been of a great help to my research.

I'd like to ask you another question.

For the market1-1 sequence from the OpenLORIS-Scene dataset, how do you align the data of d435i accelerometer and gyroscope to one topic /imu0?

And Could you open source the datasets market1-2 and market1-3 that align imu0 data? I also want to test it.

Thank you very much!

**Comment by ChenHuang20** [comment]
If it is not convenient to open source other data sets, can you send a link about them to my Email?
My Email is 450801089@qq.com.
thanks!

**Comment by karnikram** [comment]
Hi,

The script to merge the accel and gyro messages is already provided in the OpenLORIS dataset - https://gist.github.com/cedrusx/da24308e1824a6fabb0aa9f6ed7042b0. We used the same script to modify their original market-1 bagfile.

If you need the bagfiles for the other sequences with the plane segmentations topic too, we don't have them available as of now.

**Comment by ChenHuang20** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Karnik ***@***.***&gt;; 
发送时间: 2021年4月19日(星期一) 中午1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [karnikram/rp-vio] How do you align the data of d435i accelerometer and gyroscope to / imu0 topic? (#3)





 
Hi,
 
The script to merge the accel and gyro messages is already provided in the OpenLORIS dataset - https://gist.github.com/cedrusx/da24308e1824a6fabb0aa9f6ed7042b0. We used the same script to modify their original market-1 bagfile.
 
If you need the bagfiles for the other sequences with the plane segmentations topic too, we don't have them available as of now.

**Comment by Dr-cell** [comment]
> Hi，
> 
> I appreciate you can answer my question,
> 
> Thank you for your open source code and datasets.
> 
> Your work has been of a great help to my research.
> 
> I'd like to ask you another question.
> 
> For the market1-1 sequence from the OpenLORIS-Scene dataset, how do you align the data of d435i accelerometer and gyroscope to one topic /imu0?
> 
> And Could you open source the datasets market1-2 and market1-3 that align imu0 data? I also want to test it.
> 
> Thank you very much!
