### ISSUE TITLE
Question about the plane segmentation

### ISSUE THREAD

**Issue by Gatsby23** [karnikram/rp-vio#4]
Hi，I'm a freshman to the groundplane segmentation algorithm. About the inference part, how to edit the test list in the command, Like in readme.md: 
```
 --test_list=<TEST_DATA_LIST.txt FILE> 
```
for example, if I want to segment the ground plane in the left image in kitti, what should I do？ could you please give me an example about it？ I'm appreciate a lot for your wonderful help.

**Comment by sudarshan-s-harithas** [comment]
Hi, 

Please follow the steps given below to implement the plane segmentation model

1) Extract images (RGB) from your desired dataset, resize them to dimension (192,320) (height, width), and store all the images in a folder. 
2) Create a TEST_DATA_LIST.txt file, this involves creating a .txt file which consists of the path that points to individual test images 

Example: Consider the images extracted from the OpenLoris dataset, let the images be named image1.jpg, image2.jpg, ..., imagen.jpg be stored in a folder named "OpenLorisImages" now the .txt file would 
have the following lines pointing to every individual image. 

OpenLorisImages/image1
OpenLorisImages/image2
OpenLorisImages/image3
:
:
OpenLorisImages/imagen


3) Run the command  

python inference.py --dataset=<PATH_TO_DATASET> --output_dir=<PATH_TO_OUTPUT_DIRECTORY> --test_list=<TEST_DATA_LIST.txt FILE> --ckpt_file=<MODEL> --use_preprocessed=true 

here the PATH_TO_DATASET is the parent directory of the "OpenLorisImages" folder i.e PATH_TO_DATASET/OpenLorisImages/imagen.jpg should point to a given test image. 

4) The output of the above command will be stored in three folders named 

plane_sgmts: masks of image (grayscale) 
plane_sgmts_vis: color visualization of mask 
plane_sgmts_modified: grayscale masks but suitable for visualization (feed this output to the CRF inference)  


5) CRF inference 

Run  CRF inference using the command 

python crf_inference.py <rgb_image_dir> <labels_dir> <output_dir>

where the "labels_dir" is the path to the plane_sgmts_modified folder. 

Hope this helps.

**Comment by Gatsby23** [comment]
> Hi,
> 
> Please follow the steps given below to implement the plane segmentation model
> 
> 1. Extract images (RGB) from your desired dataset, resize them to dimension (192,320) (height, width), and store all the images in a folder.
> 2. Create a TEST_DATA_LIST.txt file, this involves creating a .txt file which consists of the path that points to individual test images
> 
> Example: Consider the images extracted from the OpenLoris dataset, let the images be named image1.jpg, image2.jpg, ..., imagen.jpg be stored in a folder named "OpenLorisImages" now the .txt file would
> have the following lines pointing to every individual image.
> 
> OpenLorisImages/image1
> OpenLorisImages/image2
> OpenLorisImages/image3
> :
> :
> OpenLorisImages/imagen
> 
> 1. Run the command
> 
> python inference.py --dataset=<PATH_TO_DATASET> --output_dir=<PATH_TO_OUTPUT_DIRECTORY> --test_list=<TEST_DATA_LIST.txt FILE> --ckpt_file= --use_preprocessed=true
> 
> here the PATH_TO_DATASET is the parent directory of the "OpenLorisImages" folder i.e PATH_TO_DATASET/OpenLorisImages/imagen.jpg should point to a given test image.
> 
> 1. The output of the above command will be stored in three folders named
> 
> plane_sgmts: masks of image (grayscale)
> plane_sgmts_vis: color visualization of mask
> plane_sgmts_modified: grayscale masks but suitable for visualization (feed this output to the CRF inference)
> 
> 1. CRF inference
> 
> Run CRF inference using the command
> 
> python crf_inference.py <rgb_image_dir> <labels_dir> <output_dir>
> 
> where the "labels_dir" is the path to the plane_sgmts_modified folder.
> 
> Hope this helps.

Thank you very much! I'll give it a try.
