### ISSUE TITLE
Problem with the inference.py

### ISSUE THREAD

**Issue by Gatsby23** [karnikram/rp-vio#5]
Hi, when I run python inference.py, I got this:
```
Traceback (most recent call last):
  File "inference.py", line 14, in <module>
    from RecoverPlane import RecoverPlane
ModuleNotFoundError: No module named 'RecoverPlane'

```
How can I fix this error ?

**Comment by karnikram** [comment]
Hi,

Thanks for reporting. We've updated the inference code and instructions. Please check it out and let us know if it's working for you now.

**Comment by Gatsby23** [comment]
> Hi,
> 
> Thanks for reporting. We've updated the inference code and instructions. Please check it out and let us know if it's working for you now.

Thank you very much, I'll give it a try. By the way, what is your cuda version ?

**Comment by Gatsby23** [comment]
> Hi,
> 
> Thanks for reporting. We've updated the inference code and instructions. Please check it out and let us know if it's working for you now.

I can just install the requirements in the requirments.txt, don't need to do anything else ?

**Comment by karnikram** [comment]
> Thank you very much, I'll give it a try. By the way, what is your cuda version ?
We used CUDA 9.0 as mentioned in the README.

> I can just install the requirements in the requirments.txt, don't need to do anything else ?
Yes, that environment should be enough to run the script.

**Comment by Gatsby23** [comment]
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mysql-common==8.0.21=2
  - xorg-libxdmcp==1.1.3=h516909a_0
  - zstd==1.4.5=h6597ccf_2
  - libevent==2.1.10=hcdb4288_3
  - nettle==3.6=he412f7d_0
  - xorg-xextproto==7.3.0=h14c3975_1002
  - libcblas==3.8.0=14_openblas
  - fontconfig==2.13.1=h7e3eb15_1002
```
Sorry to bothering you, but I met this error now

**Comment by Gatsby23** [comment]
> ```
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - mysql-common==8.0.21=2
>   - xorg-libxdmcp==1.1.3=h516909a_0
>   - zstd==1.4.5=h6597ccf_2
>   - libevent==2.1.10=hcdb4288_3
>   - nettle==3.6=he412f7d_0
>   - xorg-xextproto==7.3.0=h14c3975_1002
>   - libcblas==3.8.0=14_openblas
>   - fontconfig==2.13.1=h7e3eb15_1002
> ```
> 
> Sorry to bothering you, but I met this error now

But this error also exist, when I git clone the newest repository

**Comment by karnikram** [comment]
Hi, 

We are running Ubuntu 18.04. You might not be able to find the same package versions if you are running a different OS version. You may still try using different package versions.
