### ISSUE TITLE
> Hi,

### ISSUE THREAD

**Issue by ChenHuang20** [karnikram/rp-vio#7]
> Hi,
> I run vins-mono with your config file 3 times and got 1.55, 2.22, and 1.65 rmse.
> The results from VINS-Mono are more than RP-VIO.

Have you run the segmentation part ?
When I run python inference.py, I got this:

from RecoverPlane import RecoverPlane
ModuleNotFoundError: No module named 'RecoverPlane

Have you met this error before?

_Originally posted by @Gatsby23 in https://github.com/karnikram/rp-vio/issues/2#issuecomment-867651960_

**Comment by karnikram** [comment]
Duplicate of #5
