### ISSUE TITLE
Problem with the inference.py

### ISSUE THREAD

**Issue by Gatsby23** [karnikram/rp-vio#8]
Hi, Sorry to bothering you. But when I install some package that needed for plane recover library. There are also show:
```
/home/robotics/.local/lib/python3.6/site-packages/scipy/__init__.py:147: UserWarning: NumPy 1.14.5 or above is required for this version of SciPy (detected version 1.13.1)
  UserWarning)
Traceback (most recent call last):
  File "inference.py", line 14, in <module>
    from RecoverPlane import RecoverPlane
ModuleNotFoundError: No module named 'RecoverPlane'
```
But I found the RecoverPlane is in RecoverPlane_perpendicular.py python file, but I don't know how to let the inference.py to find this class ?

**Comment by sudarshan-s-harithas** [comment]
Hi, 

Please clone the latest version of RP-VIO ( from https://github.com/karnikram/rp-vio) this error has been fixed here. 

and to you need to change the line  to 
from RecoverPlane_perpendicular import RecoverPlane 
to allow inference.py find the class in RecoverPlane_perpendicular.py 

Thank You

**Comment by Gatsby23** [comment]
> Hi,
> 
> Please clone the latest version of RP-VIO ( from https://github.com/karnikram/rp-vio) this error has been fixed here.
> 
> and to you need to change the line to
> from RecoverPlane_perpendicular import RecoverPlane
> to allow inference.py find the class in RecoverPlane_perpendicular.py
> 
> Thank You

I'm really sorry, it can work now, Thank you very much
